spring:
  datasource:
    username: root
    password: gongwei911
    url: jdbc:mysql://localhost:3309/metadata?useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB


logging:
  level:
    mb: debug
    root: info
  group:
    mb: com.hthjsj.web

md:
  dev-mode: true
  server:
#    upload:
#      base-upload-path: ./upload1
    event-enabled: true
    component:
      replace-from-json-file: true
    meta-object:
      replace-from-json-file: true

  analysis:
    extension:
      meta-object-enabled: true
      meta-field-enabled: true
      component-instance-enabled: true
    db-source:
      ds1:
        username: root
        password: gongwei911
        url: jdbc:mysql://localhost:3309/metadata?useSSL=false&characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
      ds2:
        username: root
        password: gongwei911
        url: jdbc:mysql://localhost:3309/mcms?useSSL=false&characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8888